name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: devops-bluegreen-app

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.vars.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Image Tag
        id: vars
        run: echo "tag=v${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}

  deploy-to-green:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Green EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Stopping old container..."
            docker stop green-app || true
            docker rm green-app || true

            echo "Pulling new image..."
            docker pull ${{ secrets.DOCKER_USERNAME }}/devops-bluegreen-app:v${{ github.run_number }}

            echo "Starting new container..."
            docker run -d -p 3000:3000 --name green-app \
              ${{ secrets.DOCKER_USERNAME }}/devops-bluegreen-app:v${{ github.run_number }}

            echo "Deployment complete."